apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello-service
spec:
  type: ClusterIP
  selector:
    app: hello-service
  ports:
    - port: 50051
      targetPort: grpc
      protocol: TCP
